### ISSUE TITLE
Examples of C and C++ API

### ISSUE THREAD

**Issue by laanwj** [NuxiNL/argdata#2]
There are some examples of using argdata in the [cloudabi-run](https://www.freebsd.org/cgi/man.cgi?query=cloudabi-run) man page, but apart from that I've not been able to find any examples of usage.
Would be nice to have a few in this repository.

**Comment by EdSchouten** [comment]
I suspect it would make sense to provide at least three more demo apps, demonstrating:

- The C++ reading API.
- The C writing API.
- The C++ writing API.
